# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/bit_selector.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(642, 409)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout.addWidget(self.checkBox_8)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_2.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_2.addWidget(self.checkBox_16)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_3.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_19.setFont(font)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_3.addWidget(self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setObjectName("checkBox_20")
        self.verticalLayout_3.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_3.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_3.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_3.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setObjectName("checkBox_24")
        self.verticalLayout_3.addWidget(self.checkBox_24)
        self.gridLayout.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_25.setFont(font)
        self.checkBox_25.setObjectName("checkBox_25")
        self.verticalLayout_4.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName("checkBox_26")
        self.verticalLayout_4.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_27.setFont(font)
        self.checkBox_27.setObjectName("checkBox_27")
        self.verticalLayout_4.addWidget(self.checkBox_27)
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_28.setFont(font)
        self.checkBox_28.setObjectName("checkBox_28")
        self.verticalLayout_4.addWidget(self.checkBox_28)
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName("checkBox_29")
        self.verticalLayout_4.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_30.setFont(font)
        self.checkBox_30.setObjectName("checkBox_30")
        self.verticalLayout_4.addWidget(self.checkBox_30)
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_31.setFont(font)
        self.checkBox_31.setObjectName("checkBox_31")
        self.verticalLayout_4.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox_32.setFont(font)
        self.checkBox_32.setObjectName("checkBox_32")
        self.verticalLayout_4.addWidget(self.checkBox_32)
        self.gridLayout.addWidget(self.groupBox_5, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Fuse Low"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_2.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_3.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_5.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_6.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_7.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_8.setText(_translate("Dialog", "CheckBox"))
        self.groupBox_2.setTitle(_translate("Dialog", "Fuse High"))
        self.checkBox_9.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_10.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_11.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_12.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_13.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_14.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_15.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_16.setText(_translate("Dialog", "CheckBox"))
        self.groupBox_4.setTitle(_translate("Dialog", "Fuse Extra"))
        self.checkBox_17.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_18.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_19.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_20.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_21.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_22.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_23.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_24.setText(_translate("Dialog", "CheckBox"))
        self.groupBox_5.setTitle(_translate("Dialog", "Lock"))
        self.checkBox_25.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_26.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_27.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_28.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_29.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_30.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_31.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_32.setText(_translate("Dialog", "CheckBox"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.pushButton_2.setText(_translate("Dialog", "PushButton"))

