# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hmi.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidgetHMI(object):
    def setupUi(self, MainWidgetHMI):
        MainWidgetHMI.setObjectName("MainWidgetHMI")
        MainWidgetHMI.resize(500, 700)
        self.topLayout = QtWidgets.QVBoxLayout(MainWidgetHMI)
        self.topLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.topLayout.setContentsMargins(-1, 0, -1, 0)
        self.topLayout.setSpacing(6)
        self.topLayout.setObjectName("topLayout")
        self.groupBox_Serial = QtWidgets.QGroupBox(MainWidgetHMI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Serial.sizePolicy().hasHeightForWidth())
        self.groupBox_Serial.setSizePolicy(sizePolicy)
        self.groupBox_Serial.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox_Serial.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_Serial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_Serial.setObjectName("groupBox_Serial")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_Serial)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_Serial)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.portComboBox = QtWidgets.QComboBox(self.groupBox_Serial)
        self.portComboBox.setObjectName("portComboBox")
        self.horizontalLayout_2.addWidget(self.portComboBox)
        self.btnUpdatePortList = QtWidgets.QPushButton(self.groupBox_Serial)
        self.btnUpdatePortList.setObjectName("btnUpdatePortList")
        self.horizontalLayout_2.addWidget(self.btnUpdatePortList)
        self.btnPortToggle = QtWidgets.QPushButton(self.groupBox_Serial)
        self.btnPortToggle.setObjectName("btnPortToggle")
        self.horizontalLayout_2.addWidget(self.btnPortToggle)
        self.topLayout.addWidget(self.groupBox_Serial)
        self.groupBox_Terminal = QtWidgets.QGroupBox(MainWidgetHMI)
        self.groupBox_Terminal.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_Terminal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_Terminal.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_Terminal.setObjectName("groupBox_Terminal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Terminal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_terminal = QtWidgets.QTextBrowser(self.groupBox_Terminal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_terminal.sizePolicy().hasHeightForWidth())
        self.text_terminal.setSizePolicy(sizePolicy)
        self.text_terminal.setMinimumSize(QtCore.QSize(0, 60))
        self.text_terminal.setObjectName("text_terminal")
        self.verticalLayout_2.addWidget(self.text_terminal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_lineEditToBeSend = QtWidgets.QLineEdit(self.groupBox_Terminal)
        self.text_lineEditToBeSend.setEnabled(True)
        self.text_lineEditToBeSend.setMinimumSize(QtCore.QSize(0, 20))
        self.text_lineEditToBeSend.setObjectName("text_lineEditToBeSend")
        self.horizontalLayout.addWidget(self.text_lineEditToBeSend)
        self.text_btnSend = QtWidgets.QPushButton(self.groupBox_Terminal)
        self.text_btnSend.setObjectName("text_btnSend")
        self.horizontalLayout.addWidget(self.text_btnSend)
        self.text_btnClearTerminal = QtWidgets.QPushButton(self.groupBox_Terminal)
        self.text_btnClearTerminal.setObjectName("text_btnClearTerminal")
        self.horizontalLayout.addWidget(self.text_btnClearTerminal)
        self.text_btnSaveTerminal = QtWidgets.QPushButton(self.groupBox_Terminal)
        self.text_btnSaveTerminal.setObjectName("text_btnSaveTerminal")
        self.horizontalLayout.addWidget(self.text_btnSaveTerminal)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.topLayout.addWidget(self.groupBox_Terminal)
        self.groupBox_SendRead = QtWidgets.QGroupBox(MainWidgetHMI)
        self.groupBox_SendRead.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_SendRead.setObjectName("groupBox_SendRead")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_SendRead)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_SendRead)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSend = QtWidgets.QWidget()
        self.tabSend.setObjectName("tabSend")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabSend)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEditSend = QtWidgets.QTextEdit(self.tabSend)
        self.textEditSend.setObjectName("textEditSend")
        self.verticalLayout_7.addWidget(self.textEditSend)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonSendUi8ToString = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendUi8ToString.setObjectName("buttonSendUi8ToString")
        self.horizontalLayout_5.addWidget(self.buttonSendUi8ToString)
        self.buttonSendStringToUi8 = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendStringToUi8.setObjectName("buttonSendStringToUi8")
        self.horizontalLayout_5.addWidget(self.buttonSendStringToUi8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buttonSendClear = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendClear.setObjectName("buttonSendClear")
        self.verticalLayout_5.addWidget(self.buttonSendClear)
        self.buttonSendStruct = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendStruct.setObjectName("buttonSendStruct")
        self.verticalLayout_5.addWidget(self.buttonSendStruct)
        self.buttonSendArray = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendArray.setObjectName("buttonSendArray")
        self.verticalLayout_5.addWidget(self.buttonSendArray)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.buttonSendSaveFile = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendSaveFile.setObjectName("buttonSendSaveFile")
        self.verticalLayout_5.addWidget(self.buttonSendSaveFile)
        self.buttonSendReadFile = QtWidgets.QPushButton(self.tabSend)
        self.buttonSendReadFile.setObjectName("buttonSendReadFile")
        self.verticalLayout_5.addWidget(self.buttonSendReadFile)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.labelSendVerify = QtWidgets.QLabel(self.tabSend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSendVerify.sizePolicy().hasHeightForWidth())
        self.labelSendVerify.setSizePolicy(sizePolicy)
        self.labelSendVerify.setMinimumSize(QtCore.QSize(75, 23))
        self.labelSendVerify.setMaximumSize(QtCore.QSize(75, 23))
        self.labelSendVerify.setObjectName("labelSendVerify")
        self.verticalLayout_5.addWidget(self.labelSendVerify)
        self.textBrowserSendVerify = QtWidgets.QTextBrowser(self.tabSend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserSendVerify.sizePolicy().hasHeightForWidth())
        self.textBrowserSendVerify.setSizePolicy(sizePolicy)
        self.textBrowserSendVerify.setMinimumSize(QtCore.QSize(75, 25))
        self.textBrowserSendVerify.setMaximumSize(QtCore.QSize(75, 25))
        self.textBrowserSendVerify.setObjectName("textBrowserSendVerify")
        self.verticalLayout_5.addWidget(self.textBrowserSendVerify)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tabSend, "")
        self.tabReceive = QtWidgets.QWidget()
        self.tabReceive.setObjectName("tabReceive")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabReceive)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.textEditGet = QtWidgets.QTextEdit(self.tabReceive)
        self.textEditGet.setObjectName("textEditGet")
        self.verticalLayout_8.addWidget(self.textEditGet)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonGetUi8ToString = QtWidgets.QPushButton(self.tabReceive)
        self.buttonGetUi8ToString.setObjectName("buttonGetUi8ToString")
        self.horizontalLayout_7.addWidget(self.buttonGetUi8ToString)
        self.buttonGetStringToUi8 = QtWidgets.QPushButton(self.tabReceive)
        self.buttonGetStringToUi8.setObjectName("buttonGetStringToUi8")
        self.horizontalLayout_7.addWidget(self.buttonGetStringToUi8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.buttonGetClear = QtWidgets.QPushButton(self.tabReceive)
        self.buttonGetClear.setObjectName("buttonGetClear")
        self.verticalLayout_6.addWidget(self.buttonGetClear)
        self.buttonGetSaveFile = QtWidgets.QPushButton(self.tabReceive)
        self.buttonGetSaveFile.setObjectName("buttonGetSaveFile")
        self.verticalLayout_6.addWidget(self.buttonGetSaveFile)
        self.buttomGetMovetoSend = QtWidgets.QPushButton(self.tabReceive)
        self.buttomGetMovetoSend.setObjectName("buttomGetMovetoSend")
        self.verticalLayout_6.addWidget(self.buttomGetMovetoSend)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tabReceive, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.topLayout.addWidget(self.groupBox_SendRead)

        self.retranslateUi(MainWidgetHMI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidgetHMI)

    def retranslateUi(self, MainWidgetHMI):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_Serial.setTitle(_translate("MainWidgetHMI", "串列埠設定"))
        self.label.setText(_translate("MainWidgetHMI", "選擇串列埠："))
        self.btnUpdatePortList.setText(_translate("MainWidgetHMI", "更新串列埠"))
        self.btnPortToggle.setText(_translate("MainWidgetHMI", "開啟串列埠"))
        self.groupBox_Terminal.setTitle(_translate("MainWidgetHMI", "文字對話區"))
        self.text_btnSend.setText(_translate("MainWidgetHMI", "Send"))
        self.text_btnClearTerminal.setText(_translate("MainWidgetHMI", "清除對話框"))
        self.text_btnSaveTerminal.setText(_translate("MainWidgetHMI", "儲存對話框"))
        self.groupBox_SendRead.setTitle(_translate("MainWidgetHMI", "資料送收區"))
        self.buttonSendUi8ToString.setText(_translate("MainWidgetHMI", "ui8 轉 String"))
        self.buttonSendStringToUi8.setText(_translate("MainWidgetHMI", "String 轉 ui8"))
        self.buttonSendClear.setText(_translate("MainWidgetHMI", "清除暫存區"))
        self.buttonSendStruct.setText(_translate("MainWidgetHMI", "傳送結構形式"))
        self.buttonSendArray.setText(_translate("MainWidgetHMI", "傳送矩陣形式"))
        self.buttonSendSaveFile.setText(_translate("MainWidgetHMI", "儲存文字檔"))
        self.buttonSendReadFile.setText(_translate("MainWidgetHMI", "讀取文字檔"))
        self.labelSendVerify.setText(_translate("MainWidgetHMI", "資料格式驗證"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSend), _translate("MainWidgetHMI", "發送"))
        self.buttonGetUi8ToString.setText(_translate("MainWidgetHMI", "ui8 轉 String"))
        self.buttonGetStringToUi8.setText(_translate("MainWidgetHMI", "String 轉 ui8"))
        self.buttonGetClear.setText(_translate("MainWidgetHMI", "清除暫存區"))
        self.buttonGetSaveFile.setText(_translate("MainWidgetHMI", "儲存文字檔"))
        self.buttomGetMovetoSend.setText(_translate("MainWidgetHMI", "移動到發送區"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReceive), _translate("MainWidgetHMI", "接收"))

