# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hmi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidgetHMI(object):
    def setupUi(self, MainWidgetHMI):
        MainWidgetHMI.setObjectName("MainWidgetHMI")
        MainWidgetHMI.resize(900, 500)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        MainWidgetHMI.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWidgetHMI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Serial = QtWidgets.QGroupBox(MainWidgetHMI)
        self.groupBox_Serial.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Serial.sizePolicy().hasHeightForWidth())
        self.groupBox_Serial.setSizePolicy(sizePolicy)
        self.groupBox_Serial.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Serial.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_Serial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_Serial.setObjectName("groupBox_Serial")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_Serial)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.s_labelChoosePort = QtWidgets.QLabel(self.groupBox_Serial)
        self.s_labelChoosePort.setMinimumSize(QtCore.QSize(0, 24))
        self.s_labelChoosePort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.s_labelChoosePort.setBaseSize(QtCore.QSize(0, 0))
        self.s_labelChoosePort.setObjectName("s_labelChoosePort")
        self.gridLayout_3.addWidget(self.s_labelChoosePort, 0, 0, 1, 1)
        self.s_portComboBox = QtWidgets.QComboBox(self.groupBox_Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_portComboBox.sizePolicy().hasHeightForWidth())
        self.s_portComboBox.setSizePolicy(sizePolicy)
        self.s_portComboBox.setObjectName("s_portComboBox")
        self.gridLayout_3.addWidget(self.s_portComboBox, 0, 1, 1, 1)
        self.s_lineEditBaudrate = QtWidgets.QLineEdit(self.groupBox_Serial)
        self.s_lineEditBaudrate.setObjectName("s_lineEditBaudrate")
        self.gridLayout_3.addWidget(self.s_lineEditBaudrate, 1, 1, 1, 1)
        self.s_labelBaudrte = QtWidgets.QLabel(self.groupBox_Serial)
        self.s_labelBaudrte.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.s_labelBaudrte.setBaseSize(QtCore.QSize(0, 0))
        self.s_labelBaudrte.setObjectName("s_labelBaudrte")
        self.gridLayout_3.addWidget(self.s_labelBaudrte, 1, 0, 1, 1)
        self.s_btnUpdatePortList = QtWidgets.QPushButton(self.groupBox_Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_btnUpdatePortList.sizePolicy().hasHeightForWidth())
        self.s_btnUpdatePortList.setSizePolicy(sizePolicy)
        self.s_btnUpdatePortList.setObjectName("s_btnUpdatePortList")
        self.gridLayout_3.addWidget(self.s_btnUpdatePortList, 0, 2, 1, 1)
        self.s_btnPortToggle = QtWidgets.QPushButton(self.groupBox_Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_btnPortToggle.sizePolicy().hasHeightForWidth())
        self.s_btnPortToggle.setSizePolicy(sizePolicy)
        self.s_btnPortToggle.setObjectName("s_btnPortToggle")
        self.gridLayout_3.addWidget(self.s_btnPortToggle, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_Serial)
        self.groupBox_Terminal = QtWidgets.QGroupBox(MainWidgetHMI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Terminal.sizePolicy().hasHeightForWidth())
        self.groupBox_Terminal.setSizePolicy(sizePolicy)
        self.groupBox_Terminal.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_Terminal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_Terminal.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_Terminal.setObjectName("groupBox_Terminal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Terminal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_terminal = QtWidgets.QTextBrowser(self.groupBox_Terminal)
        self.text_terminal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_terminal.sizePolicy().hasHeightForWidth())
        self.text_terminal.setSizePolicy(sizePolicy)
        self.text_terminal.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.text_terminal.setFont(font)
        self.text_terminal.setObjectName("text_terminal")
        self.verticalLayout_2.addWidget(self.text_terminal)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.text_btnSend = QtWidgets.QPushButton(self.groupBox_Terminal)
        self.text_btnSend.setObjectName("text_btnSend")
        self.gridLayout_4.addWidget(self.text_btnSend, 0, 3, 1, 1)
        self.text_lineEditToBeSend = QtWidgets.QLineEdit(self.groupBox_Terminal)
        self.text_lineEditToBeSend.setEnabled(True)
        self.text_lineEditToBeSend.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.text_lineEditToBeSend.setFont(font)
        self.text_lineEditToBeSend.setObjectName("text_lineEditToBeSend")
        self.gridLayout_4.addWidget(self.text_lineEditToBeSend, 0, 0, 1, 3)
        self.text_btnSaveTerminal = QtWidgets.QPushButton(self.groupBox_Terminal)
        self.text_btnSaveTerminal.setObjectName("text_btnSaveTerminal")
        self.gridLayout_4.addWidget(self.text_btnSaveTerminal, 1, 3, 1, 1)
        self.text_btnClearTerminal = QtWidgets.QPushButton(self.groupBox_Terminal)
        self.text_btnClearTerminal.setObjectName("text_btnClearTerminal")
        self.gridLayout_4.addWidget(self.text_btnClearTerminal, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_Terminal)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(MainWidgetHMI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSend = QtWidgets.QWidget()
        self.tabSend.setObjectName("tabSend")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabSend)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.send_textEdit = QtWidgets.QTextEdit(self.tabSend)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.send_textEdit.setFont(font)
        self.send_textEdit.setObjectName("send_textEdit")
        self.verticalLayout_7.addWidget(self.send_textEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.send_labelWarn = QtWidgets.QLabel(self.tabSend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_labelWarn.sizePolicy().hasHeightForWidth())
        self.send_labelWarn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.send_labelWarn.setFont(font)
        self.send_labelWarn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.send_labelWarn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.send_labelWarn.setObjectName("send_labelWarn")
        self.horizontalLayout_6.addWidget(self.send_labelWarn)
        self.send_graphicWarn = QtWidgets.QGraphicsView(self.tabSend)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_graphicWarn.sizePolicy().hasHeightForWidth())
        self.send_graphicWarn.setSizePolicy(sizePolicy)
        self.send_graphicWarn.setMaximumSize(QtCore.QSize(20, 22))
        self.send_graphicWarn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.send_graphicWarn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.send_graphicWarn.setLineWidth(0)
        self.send_graphicWarn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_graphicWarn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_graphicWarn.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.send_graphicWarn.setObjectName("send_graphicWarn")
        self.horizontalLayout_6.addWidget(self.send_graphicWarn)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 3, 1, 1)
        self.send_btnQuickSave = QtWidgets.QPushButton(self.tabSend)
        self.send_btnQuickSave.setObjectName("send_btnQuickSave")
        self.gridLayout.addWidget(self.send_btnQuickSave, 0, 2, 1, 1)
        self.send_btnSave = QtWidgets.QPushButton(self.tabSend)
        self.send_btnSave.setObjectName("send_btnSave")
        self.gridLayout.addWidget(self.send_btnSave, 0, 1, 1, 1)
        self.send_btnAddData = QtWidgets.QPushButton(self.tabSend)
        self.send_btnAddData.setObjectName("send_btnAddData")
        self.gridLayout.addWidget(self.send_btnAddData, 1, 1, 1, 1)
        self.send_btnSend = QtWidgets.QPushButton(self.tabSend)
        self.send_btnSend.setObjectName("send_btnSend")
        self.gridLayout.addWidget(self.send_btnSend, 1, 2, 1, 1)
        self.send_btnReadFile = QtWidgets.QPushButton(self.tabSend)
        self.send_btnReadFile.setObjectName("send_btnReadFile")
        self.gridLayout.addWidget(self.send_btnReadFile, 0, 3, 1, 1)
        self.send_btnClear = QtWidgets.QPushButton(self.tabSend)
        self.send_btnClear.setMinimumSize(QtCore.QSize(80, 0))
        self.send_btnClear.setObjectName("send_btnClear")
        self.gridLayout.addWidget(self.send_btnClear, 1, 0, 1, 1)
        self.send_btnMoveToSend = QtWidgets.QPushButton(self.tabSend)
        self.send_btnMoveToSend.setMinimumSize(QtCore.QSize(80, 0))
        self.send_btnMoveToSend.setObjectName("send_btnMoveToSend")
        self.gridLayout.addWidget(self.send_btnMoveToSend, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tabSend, "")
        self.tabReceive = QtWidgets.QWidget()
        self.tabReceive.setObjectName("tabReceive")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabReceive)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rec_textEdit = QtWidgets.QTextEdit(self.tabReceive)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.rec_textEdit.setFont(font)
        self.rec_textEdit.setObjectName("rec_textEdit")
        self.verticalLayout_8.addWidget(self.rec_textEdit)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rec_labelWarn = QtWidgets.QLabel(self.tabReceive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_labelWarn.sizePolicy().hasHeightForWidth())
        self.rec_labelWarn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rec_labelWarn.setFont(font)
        self.rec_labelWarn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rec_labelWarn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rec_labelWarn.setObjectName("rec_labelWarn")
        self.horizontalLayout_7.addWidget(self.rec_labelWarn)
        self.rec_graphicWarn = QtWidgets.QGraphicsView(self.tabReceive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_graphicWarn.sizePolicy().hasHeightForWidth())
        self.rec_graphicWarn.setSizePolicy(sizePolicy)
        self.rec_graphicWarn.setMaximumSize(QtCore.QSize(20, 22))
        self.rec_graphicWarn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rec_graphicWarn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rec_graphicWarn.setLineWidth(0)
        self.rec_graphicWarn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rec_graphicWarn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rec_graphicWarn.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.rec_graphicWarn.setObjectName("rec_graphicWarn")
        self.horizontalLayout_7.addWidget(self.rec_graphicWarn)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 3, 1, 1)
        self.rec_btnQuickSave = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnQuickSave.setObjectName("rec_btnQuickSave")
        self.gridLayout_2.addWidget(self.rec_btnQuickSave, 0, 2, 1, 1)
        self.rec_btnSave = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnSave.setObjectName("rec_btnSave")
        self.gridLayout_2.addWidget(self.rec_btnSave, 0, 1, 1, 1)
        self.rec_btnAddData = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnAddData.setObjectName("rec_btnAddData")
        self.gridLayout_2.addWidget(self.rec_btnAddData, 1, 1, 1, 1)
        self.rec_btnSend = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnSend.setObjectName("rec_btnSend")
        self.gridLayout_2.addWidget(self.rec_btnSend, 1, 2, 1, 1)
        self.rec_btnReadFile = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnReadFile.setObjectName("rec_btnReadFile")
        self.gridLayout_2.addWidget(self.rec_btnReadFile, 0, 3, 1, 1)
        self.rec_btnClear = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnClear.setMinimumSize(QtCore.QSize(80, 0))
        self.rec_btnClear.setObjectName("rec_btnClear")
        self.gridLayout_2.addWidget(self.rec_btnClear, 1, 0, 1, 1)
        self.rec_btnMoveToSend = QtWidgets.QPushButton(self.tabReceive)
        self.rec_btnMoveToSend.setMinimumSize(QtCore.QSize(80, 0))
        self.rec_btnMoveToSend.setObjectName("rec_btnMoveToSend")
        self.gridLayout_2.addWidget(self.rec_btnMoveToSend, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tabReceive, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(MainWidgetHMI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidgetHMI)
        MainWidgetHMI.setTabOrder(self.s_portComboBox, self.s_btnUpdatePortList)
        MainWidgetHMI.setTabOrder(self.s_btnUpdatePortList, self.s_lineEditBaudrate)
        MainWidgetHMI.setTabOrder(self.s_lineEditBaudrate, self.s_btnPortToggle)
        MainWidgetHMI.setTabOrder(self.s_btnPortToggle, self.text_terminal)
        MainWidgetHMI.setTabOrder(self.text_terminal, self.text_lineEditToBeSend)
        MainWidgetHMI.setTabOrder(self.text_lineEditToBeSend, self.text_btnSend)
        MainWidgetHMI.setTabOrder(self.text_btnSend, self.text_btnClearTerminal)
        MainWidgetHMI.setTabOrder(self.text_btnClearTerminal, self.text_btnSaveTerminal)
        MainWidgetHMI.setTabOrder(self.text_btnSaveTerminal, self.tabWidget)
        MainWidgetHMI.setTabOrder(self.tabWidget, self.send_textEdit)
        MainWidgetHMI.setTabOrder(self.send_textEdit, self.send_btnMoveToSend)
        MainWidgetHMI.setTabOrder(self.send_btnMoveToSend, self.send_btnSave)
        MainWidgetHMI.setTabOrder(self.send_btnSave, self.send_btnQuickSave)
        MainWidgetHMI.setTabOrder(self.send_btnQuickSave, self.send_btnReadFile)
        MainWidgetHMI.setTabOrder(self.send_btnReadFile, self.send_btnClear)
        MainWidgetHMI.setTabOrder(self.send_btnClear, self.send_btnAddData)
        MainWidgetHMI.setTabOrder(self.send_btnAddData, self.send_btnSend)
        MainWidgetHMI.setTabOrder(self.send_btnSend, self.send_graphicWarn)
        MainWidgetHMI.setTabOrder(self.send_graphicWarn, self.rec_textEdit)
        MainWidgetHMI.setTabOrder(self.rec_textEdit, self.rec_btnMoveToSend)
        MainWidgetHMI.setTabOrder(self.rec_btnMoveToSend, self.rec_btnSave)
        MainWidgetHMI.setTabOrder(self.rec_btnSave, self.rec_btnQuickSave)
        MainWidgetHMI.setTabOrder(self.rec_btnQuickSave, self.rec_btnReadFile)
        MainWidgetHMI.setTabOrder(self.rec_btnReadFile, self.rec_btnClear)
        MainWidgetHMI.setTabOrder(self.rec_btnClear, self.rec_btnAddData)
        MainWidgetHMI.setTabOrder(self.rec_btnAddData, self.rec_btnSend)
        MainWidgetHMI.setTabOrder(self.rec_btnSend, self.rec_graphicWarn)

    def retranslateUi(self, MainWidgetHMI):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_Serial.setTitle(_translate("MainWidgetHMI", "串列埠設定"))
        self.s_labelChoosePort.setText(_translate("MainWidgetHMI", "選擇串列埠："))
        self.s_lineEditBaudrate.setText(_translate("MainWidgetHMI", "38400"))
        self.s_labelBaudrte.setText(_translate("MainWidgetHMI", "Baudrate"))
        self.s_btnUpdatePortList.setText(_translate("MainWidgetHMI", "更新串列埠"))
        self.s_btnPortToggle.setText(_translate("MainWidgetHMI", "開啟串列埠"))
        self.groupBox_Terminal.setTitle(_translate("MainWidgetHMI", "文字對話區"))
        self.text_btnSend.setText(_translate("MainWidgetHMI", "Send"))
        self.text_btnSaveTerminal.setText(_translate("MainWidgetHMI", "儲存對話框"))
        self.text_btnClearTerminal.setText(_translate("MainWidgetHMI", "清除對話框"))
        self.send_labelWarn.setText(_translate("MainWidgetHMI", "資料驗證："))
        self.send_btnQuickSave.setText(_translate("MainWidgetHMI", "儲存檔案"))
        self.send_btnSave.setText(_translate("MainWidgetHMI", "編輯並儲存"))
        self.send_btnAddData.setText(_translate("MainWidgetHMI", "新增資料"))
        self.send_btnSend.setText(_translate("MainWidgetHMI", "發送資料"))
        self.send_btnReadFile.setText(_translate("MainWidgetHMI", "讀取檔案"))
        self.send_btnClear.setText(_translate("MainWidgetHMI", "清除"))
        self.send_btnMoveToSend.setText(_translate("MainWidgetHMI", "接收→發送區"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSend), _translate("MainWidgetHMI", "發送"))
        self.rec_labelWarn.setText(_translate("MainWidgetHMI", "資料驗證："))
        self.rec_btnQuickSave.setText(_translate("MainWidgetHMI", "儲存檔案"))
        self.rec_btnSave.setText(_translate("MainWidgetHMI", "編輯並儲存"))
        self.rec_btnAddData.setText(_translate("MainWidgetHMI", "新增資料"))
        self.rec_btnSend.setText(_translate("MainWidgetHMI", "發送資料"))
        self.rec_btnReadFile.setText(_translate("MainWidgetHMI", "讀取檔案"))
        self.rec_btnClear.setText(_translate("MainWidgetHMI", "清除"))
        self.rec_btnMoveToSend.setText(_translate("MainWidgetHMI", "接收→發送區"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReceive), _translate("MainWidgetHMI", "接收"))

