# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hmi_new_data_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HmiNewDataDialog(object):
    def setupUi(self, HmiNewDataDialog):
        HmiNewDataDialog.setObjectName("HmiNewDataDialog")
        HmiNewDataDialog.resize(332, 278)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        HmiNewDataDialog.setFont(font)
        HmiNewDataDialog.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(HmiNewDataDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(HmiNewDataDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_array = QtWidgets.QWidget()
        self.tab_array.setObjectName("tab_array")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_array)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_abar = QtWidgets.QLabel(self.tab_array)
        self.label_abar.setObjectName("label_abar")
        self.gridLayout_5.addWidget(self.label_abar, 1, 1, 1, 1)
        self.lineEdit_anum = QtWidgets.QLineEdit(self.tab_array)
        self.lineEdit_anum.setObjectName("lineEdit_anum")
        self.gridLayout_5.addWidget(self.lineEdit_anum, 1, 2, 1, 1)
        self.label_anum = QtWidgets.QLabel(self.tab_array)
        self.label_anum.setObjectName("label_anum")
        self.gridLayout_5.addWidget(self.label_anum, 0, 2, 1, 1)
        self.label_atype = QtWidgets.QLabel(self.tab_array)
        self.label_atype.setObjectName("label_atype")
        self.gridLayout_5.addWidget(self.label_atype, 0, 0, 1, 1)
        self.comboBox_atype = QtWidgets.QComboBox(self.tab_array)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_atype.sizePolicy().hasHeightForWidth())
        self.comboBox_atype.setSizePolicy(sizePolicy)
        self.comboBox_atype.setObjectName("comboBox_atype")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.comboBox_atype.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_atype, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_aconfirm = QtWidgets.QPushButton(self.tab_array)
        self.pushButton_aconfirm.setObjectName("pushButton_aconfirm")
        self.gridLayout_6.addWidget(self.pushButton_aconfirm, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_aconsel = QtWidgets.QPushButton(self.tab_array)
        self.pushButton_aconsel.setObjectName("pushButton_aconsel")
        self.gridLayout_6.addWidget(self.pushButton_aconsel, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_array, "")
        self.tab_matrix = QtWidgets.QWidget()
        self.tab_matrix.setObjectName("tab_matrix")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_matrix)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_matrix)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_matrix)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.label_dim2 = QtWidgets.QLabel(self.tab_matrix)
        self.label_dim2.setObjectName("label_dim2")
        self.gridLayout.addWidget(self.label_dim2, 0, 4, 1, 1)
        self.lineEdit_dim1 = QtWidgets.QLineEdit(self.tab_matrix)
        self.lineEdit_dim1.setObjectName("lineEdit_dim1")
        self.gridLayout.addWidget(self.lineEdit_dim1, 1, 2, 1, 1)
        self.label_dim1 = QtWidgets.QLabel(self.tab_matrix)
        self.label_dim1.setObjectName("label_dim1")
        self.gridLayout.addWidget(self.label_dim1, 0, 2, 1, 1)
        self.lineEdit_dim2 = QtWidgets.QLineEdit(self.tab_matrix)
        self.lineEdit_dim2.setObjectName("lineEdit_dim2")
        self.gridLayout.addWidget(self.lineEdit_dim2, 1, 4, 1, 1)
        self.comboBox_mtype = QtWidgets.QComboBox(self.tab_matrix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mtype.sizePolicy().hasHeightForWidth())
        self.comboBox_mtype.setSizePolicy(sizePolicy)
        self.comboBox_mtype.setObjectName("comboBox_mtype")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.comboBox_mtype.addItem("")
        self.gridLayout.addWidget(self.comboBox_mtype, 1, 0, 1, 1)
        self.label_mtype = QtWidgets.QLabel(self.tab_matrix)
        self.label_mtype.setObjectName("label_mtype")
        self.gridLayout.addWidget(self.label_mtype, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_mconfirm = QtWidgets.QPushButton(self.tab_matrix)
        self.pushButton_mconfirm.setObjectName("pushButton_mconfirm")
        self.gridLayout_3.addWidget(self.pushButton_mconfirm, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.pushButton_mconsel = QtWidgets.QPushButton(self.tab_matrix)
        self.pushButton_mconsel.setObjectName("pushButton_mconsel")
        self.gridLayout_3.addWidget(self.pushButton_mconsel, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_matrix, "")
        self.tab_struct = QtWidgets.QWidget()
        self.tab_struct.setObjectName("tab_struct")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_struct)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_struct = QtWidgets.QGridLayout()
        self.gridLayout_struct.setObjectName("gridLayout_struct")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.tab_struct)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.tab_struct)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.gridLayout_struct.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_struct)
        self.label_8.setObjectName("label_8")
        self.gridLayout_struct.addWidget(self.label_8, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_struct)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.pushButton_sconfirm = QtWidgets.QPushButton(self.tab_struct)
        self.pushButton_sconfirm.setObjectName("pushButton_sconfirm")
        self.horizontalLayout_2.addWidget(self.pushButton_sconfirm)
        self.pushButton_sconsel = QtWidgets.QPushButton(self.tab_struct)
        self.pushButton_sconsel.setObjectName("pushButton_sconsel")
        self.horizontalLayout_2.addWidget(self.pushButton_sconsel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_struct, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(HmiNewDataDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HmiNewDataDialog)
        HmiNewDataDialog.setTabOrder(self.tabWidget, self.comboBox_atype)
        HmiNewDataDialog.setTabOrder(self.comboBox_atype, self.lineEdit_anum)
        HmiNewDataDialog.setTabOrder(self.lineEdit_anum, self.pushButton_aconfirm)
        HmiNewDataDialog.setTabOrder(self.pushButton_aconfirm, self.pushButton_aconsel)
        HmiNewDataDialog.setTabOrder(self.pushButton_aconsel, self.comboBox_mtype)
        HmiNewDataDialog.setTabOrder(self.comboBox_mtype, self.lineEdit_dim1)
        HmiNewDataDialog.setTabOrder(self.lineEdit_dim1, self.lineEdit_dim2)
        HmiNewDataDialog.setTabOrder(self.lineEdit_dim2, self.pushButton_mconfirm)
        HmiNewDataDialog.setTabOrder(self.pushButton_mconfirm, self.pushButton_mconsel)
        HmiNewDataDialog.setTabOrder(self.pushButton_mconsel, self.pushButton_sconfirm)
        HmiNewDataDialog.setTabOrder(self.pushButton_sconfirm, self.pushButton_sconsel)

    def retranslateUi(self, HmiNewDataDialog):
        _translate = QtCore.QCoreApplication.translate
        HmiNewDataDialog.setWindowTitle(_translate("HmiNewDataDialog", "新增資料視窗"))
        self.label_abar.setText(_translate("HmiNewDataDialog", "_"))
        self.label_anum.setText(_translate("HmiNewDataDialog", "數量"))
        self.label_atype.setText(_translate("HmiNewDataDialog", "型態"))
        self.comboBox_atype.setItemText(0, _translate("HmiNewDataDialog", "i8"))
        self.comboBox_atype.setItemText(1, _translate("HmiNewDataDialog", "i16"))
        self.comboBox_atype.setItemText(2, _translate("HmiNewDataDialog", "i32"))
        self.comboBox_atype.setItemText(3, _translate("HmiNewDataDialog", "i64"))
        self.comboBox_atype.setItemText(4, _translate("HmiNewDataDialog", "ui8"))
        self.comboBox_atype.setItemText(5, _translate("HmiNewDataDialog", "ui16"))
        self.comboBox_atype.setItemText(6, _translate("HmiNewDataDialog", "ui32"))
        self.comboBox_atype.setItemText(7, _translate("HmiNewDataDialog", "ui64"))
        self.comboBox_atype.setItemText(8, _translate("HmiNewDataDialog", "f32"))
        self.comboBox_atype.setItemText(9, _translate("HmiNewDataDialog", "f64"))
        self.pushButton_aconfirm.setText(_translate("HmiNewDataDialog", "確認"))
        self.pushButton_aconsel.setText(_translate("HmiNewDataDialog", "取消"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_array), _translate("HmiNewDataDialog", "陣列"))
        self.label_4.setText(_translate("HmiNewDataDialog", "_"))
        self.label_3.setText(_translate("HmiNewDataDialog", "x"))
        self.label_dim2.setText(_translate("HmiNewDataDialog", "Dim2"))
        self.label_dim1.setText(_translate("HmiNewDataDialog", "Dim1"))
        self.comboBox_mtype.setItemText(0, _translate("HmiNewDataDialog", "i8"))
        self.comboBox_mtype.setItemText(1, _translate("HmiNewDataDialog", "i16"))
        self.comboBox_mtype.setItemText(2, _translate("HmiNewDataDialog", "i32"))
        self.comboBox_mtype.setItemText(3, _translate("HmiNewDataDialog", "i64"))
        self.comboBox_mtype.setItemText(4, _translate("HmiNewDataDialog", "ui8"))
        self.comboBox_mtype.setItemText(5, _translate("HmiNewDataDialog", "ui16"))
        self.comboBox_mtype.setItemText(6, _translate("HmiNewDataDialog", "ui32"))
        self.comboBox_mtype.setItemText(7, _translate("HmiNewDataDialog", "ui64"))
        self.comboBox_mtype.setItemText(8, _translate("HmiNewDataDialog", "f32"))
        self.comboBox_mtype.setItemText(9, _translate("HmiNewDataDialog", "f64"))
        self.label_mtype.setText(_translate("HmiNewDataDialog", "型態"))
        self.pushButton_mconfirm.setText(_translate("HmiNewDataDialog", "確認"))
        self.pushButton_mconsel.setText(_translate("HmiNewDataDialog", "取消"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_matrix), _translate("HmiNewDataDialog", "矩陣"))
        self.label_7.setText(_translate("HmiNewDataDialog", "型態"))
        self.label_6.setText(_translate("HmiNewDataDialog", "數量"))
        self.label_8.setText(_translate("HmiNewDataDialog", "TextLabel"))
        self.pushButton_sconfirm.setText(_translate("HmiNewDataDialog", "確認"))
        self.pushButton_sconsel.setText(_translate("HmiNewDataDialog", "取消"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_struct), _translate("HmiNewDataDialog", "結構"))

