# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/widget_asa_loader.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetAsaLoader(object):
    def setupUi(self, WidgetAsaLoader):
        WidgetAsaLoader.setObjectName("WidgetAsaLoader")
        WidgetAsaLoader.resize(900, 500)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        WidgetAsaLoader.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetAsaLoader)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_Serial = QtWidgets.QGroupBox(WidgetAsaLoader)
        self.groupBox_Serial.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Serial.sizePolicy().hasHeightForWidth())
        self.groupBox_Serial.setSizePolicy(sizePolicy)
        self.groupBox_Serial.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Serial.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_Serial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_Serial.setObjectName("groupBox_Serial")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_Serial)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_selectPort = QtWidgets.QComboBox(self.groupBox_Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_selectPort.sizePolicy().hasHeightForWidth())
        self.comboBox_selectPort.setSizePolicy(sizePolicy)
        self.comboBox_selectPort.setObjectName("comboBox_selectPort")
        self.gridLayout_3.addWidget(self.comboBox_selectPort, 0, 1, 1, 1)
        self.pushButton_start1 = QtWidgets.QPushButton(self.groupBox_Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start1.sizePolicy().hasHeightForWidth())
        self.pushButton_start1.setSizePolicy(sizePolicy)
        self.pushButton_start1.setObjectName("pushButton_start1")
        self.gridLayout_3.addWidget(self.pushButton_start1, 1, 2, 1, 1)
        self.s_labelBaudrte = QtWidgets.QLabel(self.groupBox_Serial)
        self.s_labelBaudrte.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.s_labelBaudrte.setBaseSize(QtCore.QSize(0, 0))
        self.s_labelBaudrte.setObjectName("s_labelBaudrte")
        self.gridLayout_3.addWidget(self.s_labelBaudrte, 1, 0, 1, 1)
        self.label_selecSerialPort = QtWidgets.QLabel(self.groupBox_Serial)
        self.label_selecSerialPort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_selecSerialPort.setBaseSize(QtCore.QSize(0, 0))
        self.label_selecSerialPort.setObjectName("label_selecSerialPort")
        self.gridLayout_3.addWidget(self.label_selecSerialPort, 0, 0, 1, 1)
        self.lineEdit_Baudrate = QtWidgets.QLineEdit(self.groupBox_Serial)
        self.lineEdit_Baudrate.setObjectName("lineEdit_Baudrate")
        self.gridLayout_3.addWidget(self.lineEdit_Baudrate, 1, 1, 1, 1)
        self.pushButton_updatePortList = QtWidgets.QPushButton(self.groupBox_Serial)
        self.pushButton_updatePortList.setObjectName("pushButton_updatePortList")
        self.gridLayout_3.addWidget(self.pushButton_updatePortList, 0, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_Serial)
        self.groupBox_basicFuns = QtWidgets.QGroupBox(WidgetAsaLoader)
        self.groupBox_basicFuns.setObjectName("groupBox_basicFuns")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_basicFuns)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_basicFuns)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_statusTitle = QtWidgets.QLabel(self.groupBox)
        self.label_statusTitle.setObjectName("label_statusTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_statusTitle)
        self.label_programSizeTitle = QtWidgets.QLabel(self.groupBox)
        self.label_programSizeTitle.setObjectName("label_programSizeTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_programSizeTitle)
        self.label_programSizeContent = QtWidgets.QLabel(self.groupBox)
        self.label_programSizeContent.setObjectName("label_programSizeContent")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_programSizeContent)
        self.label_etcTitle = QtWidgets.QLabel(self.groupBox)
        self.label_etcTitle.setObjectName("label_etcTitle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_etcTitle)
        self.label_etcContent = QtWidgets.QLabel(self.groupBox)
        self.label_etcContent.setObjectName("label_etcContent")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_etcContent)
        self.label_statusContent = QtWidgets.QLabel(self.groupBox)
        self.label_statusContent.setObjectName("label_statusContent")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_statusContent)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 2)
        self.pushButton_startProg = QtWidgets.QPushButton(self.groupBox_basicFuns)
        self.pushButton_startProg.setObjectName("pushButton_startProg")
        self.gridLayout.addWidget(self.pushButton_startProg, 1, 0, 1, 1)
        self.pushButton_selectFile = QtWidgets.QPushButton(self.groupBox_basicFuns)
        self.pushButton_selectFile.setObjectName("pushButton_selectFile")
        self.gridLayout.addWidget(self.pushButton_selectFile, 0, 1, 1, 1)
        self.lineEdit_selectFile = QtWidgets.QLineEdit(self.groupBox_basicFuns)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit_selectFile.setFont(font)
        self.lineEdit_selectFile.setObjectName("lineEdit_selectFile")
        self.gridLayout.addWidget(self.lineEdit_selectFile, 0, 0, 1, 1)
        self.pushButton_stopProg = QtWidgets.QPushButton(self.groupBox_basicFuns)
        self.pushButton_stopProg.setObjectName("pushButton_stopProg")
        self.gridLayout.addWidget(self.pushButton_stopProg, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_basicFuns)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_steps = QtWidgets.QLabel(WidgetAsaLoader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_steps.sizePolicy().hasHeightForWidth())
        self.label_steps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label_steps.setFont(font)
        self.label_steps.setObjectName("label_steps")
        self.verticalLayout_4.addWidget(self.label_steps)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.groupBox_specialTools = QtWidgets.QGroupBox(WidgetAsaLoader)
        self.groupBox_specialTools.setObjectName("groupBox_specialTools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_specialTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_progStk500 = QtWidgets.QPushButton(self.groupBox_specialTools)
        self.pushButton_progStk500.setObjectName("pushButton_progStk500")
        self.verticalLayout.addWidget(self.pushButton_progStk500)
        self.verticalLayout_4.addWidget(self.groupBox_specialTools)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(WidgetAsaLoader)
        QtCore.QMetaObject.connectSlotsByName(WidgetAsaLoader)

    def retranslateUi(self, WidgetAsaLoader):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_Serial.setTitle(_translate("WidgetAsaLoader", "串列埠設定"))
        self.pushButton_start1.setText(_translate("WidgetAsaLoader", "開啟串列埠"))
        self.s_labelBaudrte.setText(_translate("WidgetAsaLoader", "Baudrate"))
        self.label_selecSerialPort.setText(_translate("WidgetAsaLoader", "選擇串列埠："))
        self.pushButton_updatePortList.setText(_translate("WidgetAsaLoader", "更新串列埠"))
        self.groupBox_basicFuns.setTitle(_translate("WidgetAsaLoader", "燒錄一般應用程式"))
        self.groupBox.setTitle(_translate("WidgetAsaLoader", "燒錄狀態"))
        self.label_statusTitle.setText(_translate("WidgetAsaLoader", "當前狀態："))
        self.label_programSizeTitle.setText(_translate("WidgetAsaLoader", "程式大小："))
        self.label_programSizeContent.setText(_translate("WidgetAsaLoader", "-"))
        self.label_etcTitle.setText(_translate("WidgetAsaLoader", "預估花費時間："))
        self.label_etcContent.setText(_translate("WidgetAsaLoader", "-"))
        self.label_statusContent.setText(_translate("WidgetAsaLoader", "等待燒錄"))
        self.pushButton_startProg.setText(_translate("WidgetAsaLoader", "開始燒錄"))
        self.pushButton_selectFile.setText(_translate("WidgetAsaLoader", "選擇檔案"))
        self.pushButton_stopProg.setText(_translate("WidgetAsaLoader", "強制終止"))
        self.label_steps.setText(_translate("WidgetAsaLoader", "<html><head/><body><p>1. 用USB線將ASA_M128與電腦接上。</p><p>2. 將ASA_M128指撥開關撥到&quot;prog&quot;，並按下reset按鈕。</p><p>3. 選擇ASA_M128連接到之串列埠。</p><p>4. 點選選擇檔案，並選取欲燒錄之檔案。</p><p>5. 點選開始燒錄。</p><p>6. 等待下方進度條跑到100%即完成燒錄。</p></body></html>"))
        self.groupBox_specialTools.setTitle(_translate("WidgetAsaLoader", "燒錄特殊功能應用程式"))
        self.pushButton_progStk500.setText(_translate("WidgetAsaLoader", "燒錄 \"M128_STK500\"  (可將ASA_M128轉變為STK500裝置使用)"))

