# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/asa_prog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidgetAsaProg(object):
    def setupUi(self, MainWidgetAsaProg):
        MainWidgetAsaProg.setObjectName("MainWidgetAsaProg")
        MainWidgetAsaProg.resize(500, 700)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        MainWidgetAsaProg.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MainWidgetAsaProg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_serial = QtWidgets.QGroupBox(MainWidgetAsaProg)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_serial)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_selecSerialPort = QtWidgets.QLabel(self.groupBox_serial)
        self.label_selecSerialPort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_selecSerialPort.setBaseSize(QtCore.QSize(0, 0))
        self.label_selecSerialPort.setObjectName("label_selecSerialPort")
        self.horizontalLayout_2.addWidget(self.label_selecSerialPort)
        self.comboBox_selectPort = QtWidgets.QComboBox(self.groupBox_serial)
        self.comboBox_selectPort.setObjectName("comboBox_selectPort")
        self.horizontalLayout_2.addWidget(self.comboBox_selectPort)
        self.pushButton_updatePortList = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_updatePortList.setObjectName("pushButton_updatePortList")
        self.horizontalLayout_2.addWidget(self.pushButton_updatePortList)
        self.verticalLayout_3.addWidget(self.groupBox_serial)
        self.groupBox_SelectFile = QtWidgets.QGroupBox(MainWidgetAsaProg)
        self.groupBox_SelectFile.setObjectName("groupBox_SelectFile")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_SelectFile)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_selectFile = QtWidgets.QPushButton(self.groupBox_SelectFile)
        self.pushButton_selectFile.setObjectName("pushButton_selectFile")
        self.gridLayout.addWidget(self.pushButton_selectFile, 0, 1, 1, 1)
        self.lineEdit_selectFile = QtWidgets.QLineEdit(self.groupBox_SelectFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit_selectFile.setFont(font)
        self.lineEdit_selectFile.setObjectName("lineEdit_selectFile")
        self.gridLayout.addWidget(self.lineEdit_selectFile, 0, 0, 1, 1)
        self.label_steps = QtWidgets.QLabel(self.groupBox_SelectFile)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label_steps.setFont(font)
        self.label_steps.setObjectName("label_steps")
        self.gridLayout.addWidget(self.label_steps, 2, 0, 1, 3)
        self.pushButton_startProg = QtWidgets.QPushButton(self.groupBox_SelectFile)
        self.pushButton_startProg.setObjectName("pushButton_startProg")
        self.gridLayout.addWidget(self.pushButton_startProg, 1, 0, 1, 1)
        self.pushButton_stopProg = QtWidgets.QPushButton(self.groupBox_SelectFile)
        self.pushButton_stopProg.setObjectName("pushButton_stopProg")
        self.gridLayout.addWidget(self.pushButton_stopProg, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_SelectFile)
        self.groupBox_specialTools = QtWidgets.QGroupBox(MainWidgetAsaProg)
        self.groupBox_specialTools.setObjectName("groupBox_specialTools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_specialTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_progStk500 = QtWidgets.QPushButton(self.groupBox_specialTools)
        self.pushButton_progStk500.setObjectName("pushButton_progStk500")
        self.verticalLayout.addWidget(self.pushButton_progStk500)
        self.verticalLayout_3.addWidget(self.groupBox_specialTools)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(MainWidgetAsaProg)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(MainWidgetAsaProg)
        QtCore.QMetaObject.connectSlotsByName(MainWidgetAsaProg)

    def retranslateUi(self, MainWidgetAsaProg):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_serial.setTitle(_translate("MainWidgetAsaProg", "串列埠設定"))
        self.label_selecSerialPort.setText(_translate("MainWidgetAsaProg", "選擇串列埠："))
        self.pushButton_updatePortList.setText(_translate("MainWidgetAsaProg", "更新串列埠"))
        self.groupBox_SelectFile.setTitle(_translate("MainWidgetAsaProg", "燒錄一般應用程式"))
        self.pushButton_selectFile.setText(_translate("MainWidgetAsaProg", "選擇檔案"))
        self.label_steps.setText(_translate("MainWidgetAsaProg", "<html><head/><body><p>1. 用USB線將ASA_M128與電腦接上。</p><p>2. 將ASA_M128指撥開關撥到&quot;prog&quot;，並按下reset按鈕。</p><p>3. 選擇ASA_M128連接到之串列埠。</p><p>4. 點選選擇檔案，並選取欲燒錄之檔案。</p><p>5. 點選開始燒錄。</p><p>6. 等待下方進度條跑到100%即完成燒錄。</p></body></html>"))
        self.pushButton_startProg.setText(_translate("MainWidgetAsaProg", "開始燒錄"))
        self.pushButton_stopProg.setText(_translate("MainWidgetAsaProg", "強制終止"))
        self.groupBox_specialTools.setTitle(_translate("MainWidgetAsaProg", "燒錄特殊功能應用程式"))
        self.pushButton_progStk500.setText(_translate("MainWidgetAsaProg", "燒錄 \"M128_STK500\" "))

