# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/asa_prog_qc.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidgetAsaProgQc(object):
    def setupUi(self, MainWidgetAsaProgQc):
        MainWidgetAsaProgQc.setObjectName("MainWidgetAsaProgQc")
        MainWidgetAsaProgQc.resize(500, 700)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        MainWidgetAsaProgQc.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MainWidgetAsaProgQc)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_serial = QtWidgets.QGroupBox(MainWidgetAsaProgQc)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_serial)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_selecSerialPort = QtWidgets.QLabel(self.groupBox_serial)
        self.label_selecSerialPort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_selecSerialPort.setBaseSize(QtCore.QSize(0, 0))
        self.label_selecSerialPort.setObjectName("label_selecSerialPort")
        self.horizontalLayout_2.addWidget(self.label_selecSerialPort)
        self.comboBox_selectPort = QtWidgets.QComboBox(self.groupBox_serial)
        self.comboBox_selectPort.setObjectName("comboBox_selectPort")
        self.horizontalLayout_2.addWidget(self.comboBox_selectPort)
        self.pushButton_updatePortList = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_updatePortList.setObjectName("pushButton_updatePortList")
        self.horizontalLayout_2.addWidget(self.pushButton_updatePortList)
        self.verticalLayout_3.addWidget(self.groupBox_serial)
        self.groupBox_basicFuns = QtWidgets.QGroupBox(MainWidgetAsaProgQc)
        self.groupBox_basicFuns.setObjectName("groupBox_basicFuns")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_basicFuns)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_selectFile = QtWidgets.QLineEdit(self.groupBox_basicFuns)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit_selectFile.setFont(font)
        self.lineEdit_selectFile.setObjectName("lineEdit_selectFile")
        self.gridLayout.addWidget(self.lineEdit_selectFile, 2, 0, 1, 1)
        self.pushButton_selectFile = QtWidgets.QPushButton(self.groupBox_basicFuns)
        self.pushButton_selectFile.setObjectName("pushButton_selectFile")
        self.gridLayout.addWidget(self.pushButton_selectFile, 2, 1, 1, 1)
        self.label_steps = QtWidgets.QLabel(self.groupBox_basicFuns)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label_steps.setFont(font)
        self.label_steps.setObjectName("label_steps")
        self.gridLayout.addWidget(self.label_steps, 4, 0, 1, 3)
        self.pushButton_startProg = QtWidgets.QPushButton(self.groupBox_basicFuns)
        self.pushButton_startProg.setObjectName("pushButton_startProg")
        self.gridLayout.addWidget(self.pushButton_startProg, 3, 0, 1, 1)
        self.pushButton_stopProg = QtWidgets.QPushButton(self.groupBox_basicFuns)
        self.pushButton_stopProg.setObjectName("pushButton_stopProg")
        self.gridLayout.addWidget(self.pushButton_stopProg, 3, 1, 1, 1)
        self.label_inputNum = QtWidgets.QLabel(self.groupBox_basicFuns)
        self.label_inputNum.setObjectName("label_inputNum")
        self.gridLayout.addWidget(self.label_inputNum, 1, 0, 1, 1)
        self.lineEdit_num = QtWidgets.QLineEdit(self.groupBox_basicFuns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_num.sizePolicy().hasHeightForWidth())
        self.lineEdit_num.setSizePolicy(sizePolicy)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.gridLayout.addWidget(self.lineEdit_num, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_basicFuns)
        self.groupBox = QtWidgets.QGroupBox(MainWidgetAsaProgQc)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_statusTitle = QtWidgets.QLabel(self.groupBox)
        self.label_statusTitle.setObjectName("label_statusTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_statusTitle)
        self.label_programSizeTitle = QtWidgets.QLabel(self.groupBox)
        self.label_programSizeTitle.setObjectName("label_programSizeTitle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_programSizeTitle)
        self.label_programSizeContent = QtWidgets.QLabel(self.groupBox)
        self.label_programSizeContent.setObjectName("label_programSizeContent")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_programSizeContent)
        self.label_etcTitle = QtWidgets.QLabel(self.groupBox)
        self.label_etcTitle.setObjectName("label_etcTitle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_etcTitle)
        self.label_etcContent = QtWidgets.QLabel(self.groupBox)
        self.label_etcContent.setObjectName("label_etcContent")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_etcContent)
        self.label_statusContent = QtWidgets.QLabel(self.groupBox)
        self.label_statusContent.setObjectName("label_statusContent")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_statusContent)
        self.label_progedNum = QtWidgets.QLabel(self.groupBox)
        self.label_progedNum.setObjectName("label_progedNum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_progedNum)
        self.label_progedNumContent = QtWidgets.QLabel(self.groupBox)
        self.label_progedNumContent.setObjectName("label_progedNumContent")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_progedNumContent)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(MainWidgetAsaProgQc)
        QtCore.QMetaObject.connectSlotsByName(MainWidgetAsaProgQc)

    def retranslateUi(self, MainWidgetAsaProgQc):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_serial.setTitle(_translate("MainWidgetAsaProgQc", "串列埠設定"))
        self.label_selecSerialPort.setText(_translate("MainWidgetAsaProgQc", "選擇QC程序控制治具串列埠："))
        self.pushButton_updatePortList.setText(_translate("MainWidgetAsaProgQc", "更新串列埠"))
        self.groupBox_basicFuns.setTitle(_translate("MainWidgetAsaProgQc", "燒錄一般應用程式"))
        self.pushButton_selectFile.setText(_translate("MainWidgetAsaProgQc", "選擇檔案"))
        self.label_steps.setText(_translate("MainWidgetAsaProgQc", "<html><head/><body><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>"))
        self.pushButton_startProg.setText(_translate("MainWidgetAsaProgQc", "開始連續燒錄"))
        self.pushButton_stopProg.setText(_translate("MainWidgetAsaProgQc", "強制終止"))
        self.label_inputNum.setText(_translate("MainWidgetAsaProgQc", "輸入燒錄數量："))
        self.groupBox.setTitle(_translate("MainWidgetAsaProgQc", "燒錄狀態"))
        self.label_statusTitle.setText(_translate("MainWidgetAsaProgQc", "當前狀態："))
        self.label_programSizeTitle.setText(_translate("MainWidgetAsaProgQc", "程式大小："))
        self.label_programSizeContent.setText(_translate("MainWidgetAsaProgQc", "-"))
        self.label_etcTitle.setText(_translate("MainWidgetAsaProgQc", "預估花費時間："))
        self.label_etcContent.setText(_translate("MainWidgetAsaProgQc", "-"))
        self.label_statusContent.setText(_translate("MainWidgetAsaProgQc", "等待燒錄"))
        self.label_progedNum.setText(_translate("MainWidgetAsaProgQc", "已燒錄數量："))
        self.label_progedNumContent.setText(_translate("MainWidgetAsaProgQc", "-"))

